name = "popekyrillos-store"
main = "cloudflare-worker.js"
compatibility_date = "2026-06-19"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
